apps/goods/urls.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author: wang
# Date: 18/06/24 13:36

from django.conf.urls import url
from .views import GoodsView,GoodsInfoView,AddShoppingBase


urlpatterns = [
    url(r'^list/$', GoodsView.as_view(), name="list"),
    url(r'^info/(?P<goods_id>\d+)$', GoodsInfoView.as_view(), name="info"),
    url(r'^add_shopping_base/$', AddShoppingBase.as_view(), name="add_shopping_base"),
]

apps/operation/urls.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author: wang
# Date: 18/07/01 13:36


from django.conf.urls import url

from .views import AboutView, PayTypeView, CustomerCouponView, CustomerAddressView, CustomerOrderView, OrderCancelView, \
    OrderInfoView,ShoppingBaseView,ChannelShoppingBaseView,SubShoppingNums,AddShoppingNums,CourseComment

urlpatterns = [
    url(r'^about/$', AboutView.as_view(), name="about"),
    url(r'^pay_type/$', PayTypeView.as_view(), name="pay_type"),
    url(r'^user_coupon/$', CustomerCouponView.as_view(), name="user_coupon"),
    url(r'^user_address/$', CustomerAddressView.as_view(), name="user_address"),
    url(r'^user_order/(?P<order_status>\d+)$', CustomerOrderView.as_view(), name="user_order"),
    url(r'^order_cancel/(?P<order_id>\d+)$', OrderCancelView.as_view(), name="order_cancel"),
    url(r'^order_info/(?P<order_id>\d+)$', OrderInfoView.as_view(), name="order_info"),
    url(r'^shopping_base/$', ShoppingBaseView.as_view(), name="shopping_base"),
    url(r'^base_channel/(?P<list_id>\d+)$', ChannelShoppingBaseView.as_view(), name="base_channel"),
    url(r'^add_num/(?P<list_id>\d+)$', AddShoppingNums.as_view(), name="add_num"),
    url(r'^sub_num/(?P<list_id>\d+)$', SubShoppingNums.as_view(), name="sub_num"),
    url(r'^course_comments/$', CourseComment.as_view(), name="course_comments"),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

flower_say/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from flower_say.settings import MEDIA_ROOT
from extra_apps import xadmin
from django.views.generic import TemplateView
from apps.users.views import LoginView,RegisterView
from apps.operation.views import IndexView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # 富文本编辑器
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # 首页
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name="login"),
    # 用户注册
    url(r'^register/$', RegisterView.as_view(), name="register"),
    # 验证码URL
    url(r'^captcha/', include('captcha.urls')),
    # 商品url配置
    url(r'^shopping/', include('apps.goods.urls', namespace="goods")),
    # 通用url配置
    url(r'^operation/', include('apps.operation.urls', namespace="operation")),
    # 门店url配置
    url(r'^stores/', include('apps.stores.urls', namespace="stores")),
    # 用户url配置
    url(r'^user/', include('apps.users.urls', namespace="user")),
]

apps/users/forms.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author: wang
# Date: 18/07/04 16:37

from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile


# 验证表单
class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    # 验证码,参数：错误信息
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})


class UserInforForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'first_name', 'last_name', 'birthday', 'mobile']


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/customer_coupon.html
{% extends 'customer_base.html' %}
{% block rightslider %}
    <div class="usermanage_rightslider"
         style="border:1px solid #ddd;padding-bottom:20px;vertical-align: top;display:none;">
        <div class="usermanage_content">
            <div class="bit-order-list">
                <div class="my_new_order_h2 ">
                    <a class="onlyleft" style="margin-left:15px;cursor:pointer;" onclick="open_user_back();"><span
                            class="fa fa-angle-left"></span>返回</a>
                    <i class="fa fa-tags onlyright" style="margin-right:10px;"></i>
                    优惠劵
                </div>
                <div class="my_tab_content">
                    <div class="order_list" style="position:relative;">
                        <div class="order_detail">
                            <div id="coupons_list">
                                <table border="1" width="100%">
                                    <thead>
                                    <tr>
                                        <th>优惠券名</th>
                                        <th>价格</th>
                                        <th>开始时间</th>
                                        <th>结束时间</th>
                                    </tr>
                                    </thead>
                                    <tbody align="center">
                                    {% for coupon in user_coupon %}
                                        <tr>
                                            <td>{{ coupon.course }}</td>
                                            <td>{{ coupon.price }}</td>
                                            <td>{{ coupon.start_date }}</td>
                                            <td>{{ coupon.end_date }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/customer_order.html
{% extends 'customer_base.html' %}
{% block title %}我的订单--花语{% endblock %}
{% block rightslider %}
    <div class="usermanage_rightslider"
         style="border:1px solid #ddd;padding-bottom:20px;vertical-align: top;display:none;">
        <div class="usermanage_content">
            <div class="bit-order-list">
                <div class="my_new_order_h2 ">
                    <a class="onlyleft" style="margin-left:15px;cursor:pointer;" onclick="open_user_back();">
                        <span class="fa fa-angle-left"></span>
                        返回
                    </a>
                    <i class="fa fa-calculator onlyright" style="margin-right:10px;"></i>
                    我的订单
                </div>

                <div class="my_tab">
                    <div class="buttons-tab">
                        <a href="{% url 'operation:user_order' 0 %}"
                           class="tab-link {% ifequal order_status 0 %}active{% endifequal %} orderbutton">全部订单</a>
                        <a href="{% url 'operation:user_order' 1 %}"
                           class="tab-link {% ifequal order_status 1 %}active{% endifequal %} orderbutton">等待中</a><a
                            href="{% url 'operation:user_order' 2 %}"
                            class="tab-link {% ifequal order_status 2 %}active{% endifequal %} orderbutton">已取消</a>
                    </div>
                </div>
                <div class="my_tab_content">
                    <div class="order_list" style="position:relative;">
                        {% if not orders %}
                            <div class="empty" style="text-align:center;">
                                <i class="fa-dropbox fa" style="font-size:150px;color:#EDEDED;padding:20px;"></i>
                            </div>
                        {% else %}
                            <div class="my_tab_content">
                                <div class="order_list" style="position:relative;">
                                    {% for order in orders %}
                                        <div class="order_detail">
                                            <div class="order_header">
                                            <span class="order_id">订单： <a style="cursor:pointer;"
                                                                          href="/operation/order_info/{{ order.id }}">#{{ order.id }}</a></span><span
                                                    class="order_status">状态：{{ order.status }}</span>
                                                <span class="order_desc"></span><span class="order_date"><span
                                                    class="wf-mobile-hidden">日期：{{ order.add_time }}</span></span> <span
                                                    class="order_money">合计：<span
                                                    class="amount">¥{{ order.all_pirce }}</span></span>
                                                <span style="clear:both;"></span>
                                            </div>
                                            <div class="order_content_container">
                                                <div class="shop_table order_content">
                                                    <div class="p_name">
                                                        <div class="p_image">
                                                            <a href="{% url 'goods:info' order.course.id %}"
                                                               target="_blank">
                                                                <img width="90" height="90"
                                                                     src="{{ MEDIA_URL }}{{ order.course.image }}"
                                                                     class="attachment-shop_thumbnail qf-post-image"
                                                                     alt=" "
                                                                     title=" " description="" data-title="p-7-300x300">
                                                            </a>

                                                        </div>
                                                        <div class="p_blank_1 p_blank"></div>
                                                        <div class="p_title">
                                                            <a href="{% url 'goods:info' order.course.id %}"
                                                               target="_blank">
                                                                {{ order.course.name }} </a>
                                                        </div>
                                                    </div>
                                                    <div class="p_price">
                                                        {{ order.course.price }}.00 <strong
                                                            class="product-quantity">× {{ order.nums }}</strong></div>
                                                    <div class="p_subprice">
                                                        <span class="amount">¥{{ order.course.price }}</span></div>
                                                </div>
                                            </div>
                                            <div class="order_footer">
                                                {% ifequal order.status '未支付' %}
                                                    <a style="margin-left:10px;" target="_blank"
                                                       href="http://59dadbbaac436.t74.qifeiye.com/?page_id=9621&amp;order-pay=15872&amp;pay_for_order=true&amp;key=wc_order_5b41cbfde0b1a"
                                                       class=" pay">付款</a>
                                                {% endifequal %}
                                                {% ifnotequal order.status '取消' %}
                                                    <a style="margin-left:10px;cursor:pointer;"
                                                       href="{% url "operation:order_cancel" order.id %}"
                                                       class=" cancel">取消</a>
                                                {% endifnotequal %}<a
                                                    style="margin-left:10px;cursor:pointer;"
                                                    href="{% url "operation:order_info" order.id %}"
                                                    class=" view">查看</a></div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>{% endblock %}

templates/order_info.html
{% extends 'customer_base.html' %}
{% load staticfiles %}
{% block title %}订单详情--花语{% endblock %}
{% block rightslider %}
    <div class="usermanage_rightslider"
         style="border:1px solid #ddd;padding-bottom:20px;vertical-align: top;display:none;">
        <div class="usermanage_content">
            <div class="bit-order-list">
                <div class="my_new_order_h2 ">
                    <a class="onlyleft" style="margin-left:15px;cursor:pointer;" onclick="open_user_back();"><span
                            class="fa fa-angle-left"></span>返回</a>
                    <i class="fa fa- onlyright" style="margin-right:10px;"></i>订单详情 <a class="backbtn onlyright"
                                                                                       style="cursor:pointer;float: right;margin-right:1px;"
                                                                                       href="{% url "operation:user_order" 0 %}"><span
                        class="fa fa-reply"></span></a>
                </div>


                <div class="my_tab_content">
                    <div class="order_list" style="position:relative;min-height:300px;">

                        <div class="order_detail">
                            <h2>订单详情</h2>
                            <table class="shop_table order_details">
                                <thead>
                                <tr>
                                    <th class="product-name">商品</th>
                                    <th class="product-total">合计</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr class="cart-subtotal">
                                    <th scope="row">购物小计：</th>
                                    <td style=""><span class="amount">¥{{ order.all_price }}</span></td>
                                </tr>
                                <tr class="">
                                    <th scope="row">配送:</th>
                                    <td style="">免费送货</td>
                                </tr>
                                <tr class="order-total">
                                    <th scope="row">订单合计：</th>
                                    <td style="font-weight:bold"><span class="amount">¥{{ order.all_price }}</span></td>
                                </tr>
                                </tfoot>
                                <tbody>
                                <tr data-proid="13001" class="order_item">
                                    <td class="product-name mainProductname">
                                        <a href="{% url 'goods:info' order.course.id %}">
                                            {{ order.course.name }} <strong
                                                class="product-quantity">× {{ order.nums }}</strong> </a>

                                    </td>
                                    <td class="product-total mainProductname">
                                        <span class="amount">¥{{ order.all_price }}</span></td>
                                </tr>
                                </tbody>
                            </table>

                            <header>
                                <h2>客户详情</h2>
                            </header>
                            <table class="customer_details shop_table">
                                <tbody>
                                <tr>
                                    <th width="80">Email:</th>
                                    <td>{{ order.user.email }}</td>
                                </tr>
                                <tr>
                                    <th>电话：</th>
                                    <td>{{ order_address.shou_phone }}</td>
                                </tr>

                                <tr>
                                    <td colspan="2" style="padding-left:15px;" class="address_wrap">


                                        <div class="col2-set addresses">

                                            <div class="col-1">


                                                <header class="title">
                                                    <h3>账单地址</h3>
                                                </header>
                                                <address><p>
                                                    城市：<br>
                                                    &nbsp;&nbsp;{{ order_address.city.name }}<br>
                                                    收货地址：<br>
                                                    &nbsp;&nbsp;{{ order_address.shou_address }}<br>
                                                    收件人：<br>
                                                    &nbsp;&nbsp;{{ order_address.shou_name }} </p></address>


                                            </div>

                                        </div>

                                    </td>
                                </tr>


                                </tbody>
                            </table>
                            <div class="clear"></div>

                            <div style="padding:20px 0;"><a href="http://59dadbbaac436.t74.qifeiye.com/?page_id=15787#"
                                                            onclick="toorderpage(&quot;15787&quot;)"
                                                            class="button second_button back">返回</a></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}